apiVersion: batch/v1
kind: Job
metadata:
  name: merge-lefover-hdf5
spec:
  template:
    spec:
      containers:
      - name: hdf5-container
        image: ilcsoft/py3lcio:lcio-16
        env:
        - name: TARGET
          value: /eos/user/e/eneren/run_prod50k/hdf5
        command: ["/bin/bash", "-c"]
        args: 
         - cd LCIO; source setup.sh; cd ..;
           cp /secret/krb-secret-vol/krb5cc_1000 /tmp/krb5cc_0 && chmod 600 /tmp/krb5cc_0;
           conda init bash; source /root/.bashrc; conda activate root_env && cd $TARGET;
           git clone https://github.com/EnginEren/hgAHCal-ECal.git && cd $PWD/hgAHCal-ECal;
           f=$(ls | tr '\n' ' ') && python combineEOS.py --input $f --output merged_lefover.hdf5;
           rm -rf hgAHCal-ECal;
        volumeMounts:
        - {mountPath: /eos, name: eos}
        - {mountPath: /secret/krb-secret-vol, name: krb-secret-vol}
      restartPolicy: Never
      volumes:
      - hostPath: {path: /var/eos}
        name: eos
      - name: krb-secret-vol
        secret: {secretName: krb-secret}
      
        

  backoffLimit: 1

---