apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ildeventgen-nestedgan-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9, pipelines.kubeflow.org/pipeline_compilation_time: '2022-02-01T13:34:24.208559',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Event Simulation and Reconstruction",
      "name": "ILDEventGen_NestedGAN"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9}
spec:
  entrypoint: ildeventgen-nestedgan
  templates:
  - name: ildeventgen-nestedgan
    dag:
      tasks:
      - {name: persistent-volume, template: persistent-volume}
      - name: reconstruction
        template: reconstruction
        dependencies: [persistent-volume, simulation]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
          artifacts:
          - {name: simulation-data, from: '{{tasks.simulation.outputs.artifacts.simulation-data}}'}
      - name: simulation
        template: simulation
        dependencies: [persistent-volume]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
  - name: persistent-volume
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.name}}-my-pvc'
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
    outputs:
      parameters:
      - name: persistent-volume-manifest
        valueFrom: {jsonPath: '{}'}
      - name: persistent-volume-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: persistent-volume-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: reconstruction
    container:
      args: ['git clone https://github.com/EnginEren/hgAHCal-ECal.git &&                                 cd
          $PWD/hgAHCal-ECal && pwd &&                                 chmod +x ./runRec.sh
          && ./runRec.sh "$0"', /tmp/inputs/input-0/data]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-spack:latest
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
      artifacts:
      - {name: simulation-data, path: /tmp/inputs/input-0/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: simulation
    container:
      args: ['git clone https://github.com/EnginEren/hgAHCal-ECal.git  &&                                 cd
          $PWD/hgAHCal-ECal && chmod +x ./runSimNested.sh && ./runSimNested.sh "$0"
          "$1" ', '1', testNested]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-spack:latest
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
    outputs:
      artifacts:
      - {name: simulation-data, path: /mnt/run_testNested/pion-shower_1.slcio}
      - {name: simulation-lcio_path, path: /mnt/lcio_path}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
