apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ildeventgen-nestedgan-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9, pipelines.kubeflow.org/pipeline_compilation_time: '2022-03-01T16:02:57.495519',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Event Simulation and Reconstruction",
      "name": "ILDEventGen_NestedGAN"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9}
spec:
  entrypoint: ildeventgen-nestedgan
  templates:
  - name: control-plots
    container:
      args: ['cd LCIO; source setup.sh; cd .. &&                                 conda
          init bash; source /root/.bashrc; conda activate root_env && mkdir -p /mnt/plots
          &&                                 git clone https://github.com/EnginEren/hgAHCal-ECal.git
          && cd $PWD/hgAHCal-ECal &&                                 python control.py
          --lcio "$0" --h5file "$1" --nEvents 1000 &&                                 cd
          /mnt/plots/ && touch pion_plots.tar.gz &&                                 tar
          --exclude=pion_plots.tar.gz -zcvf pion_plots.tar.gz .', /tmp/inputs/input-0/data,
        /tmp/inputs/input-1/data]
      command: [/bin/bash, -c]
      image: ilcsoft/py3lcio:lcio-16
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
      artifacts:
      - {name: reconstruction-3-data, path: /tmp/inputs/input-0/data}
      - {name: hdf5-conversion-3-data, path: /tmp/inputs/input-1/data}
    outputs:
      artifacts:
      - {name: control-plots-data, path: /mnt/plots/pion_plots.tar.gz}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: hdf5-conversion
    container:
      args: ['cd LCIO; source setup.sh; cd .. &&                                 conda
          init bash; source /root/.bashrc; conda activate root_env &&                                 git
          clone https://github.com/EnginEren/hgAHCal-ECal.git && cd $PWD/hgAHCal-ECal                                  &&
          python create_hdf5.py --lcio "$0" --outputR "$1" --outputP "$2" --nEvents
          1000', /tmp/inputs/input-0/data, prod, '1']
      command: [/bin/bash, -c]
      image: ilcsoft/py3lcio:lcio-16
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
      artifacts:
      - {name: reconstruction-data, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: hdf5-conversion-data, path: /mnt/run_prod/pion-shower_1.tar.gz}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: hdf5-conversion-2
    container:
      args: ['cd LCIO; source setup.sh; cd .. &&                                 conda
          init bash; source /root/.bashrc; conda activate root_env &&                                 git
          clone https://github.com/EnginEren/hgAHCal-ECal.git && cd $PWD/hgAHCal-ECal                                  &&
          python create_hdf5.py --lcio "$0" --outputR "$1" --outputP "$2" --nEvents
          1000', /tmp/inputs/input-0/data, prod, '2']
      command: [/bin/bash, -c]
      image: ilcsoft/py3lcio:lcio-16
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
      artifacts:
      - {name: reconstruction-2-data, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: hdf5-conversion-2-data, path: /mnt/run_prod/pion-shower_2.tar.gz}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: hdf5-conversion-3
    container:
      args: ['cd LCIO; source setup.sh; cd .. &&                                 conda
          init bash; source /root/.bashrc; conda activate root_env &&                                 git
          clone https://github.com/EnginEren/hgAHCal-ECal.git && cd $PWD/hgAHCal-ECal                                  &&
          python create_hdf5.py --lcio "$0" --outputR "$1" --outputP "$2" --nEvents
          1000', /tmp/inputs/input-0/data, prod, '3']
      command: [/bin/bash, -c]
      image: ilcsoft/py3lcio:lcio-16
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
      artifacts:
      - {name: reconstruction-3-data, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: hdf5-conversion-3-data, path: /mnt/run_prod/pion-shower_3.tar.gz}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: ildeventgen-nestedgan
    dag:
      tasks:
      - name: control-plots
        template: control-plots
        dependencies: [hdf5-conversion-3, persistent-volume, reconstruction-3]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
          artifacts:
          - {name: hdf5-conversion-3-data, from: '{{tasks.hdf5-conversion-3.outputs.artifacts.hdf5-conversion-3-data}}'}
          - {name: reconstruction-3-data, from: '{{tasks.reconstruction-3.outputs.artifacts.reconstruction-3-data}}'}
      - name: hdf5-conversion
        template: hdf5-conversion
        dependencies: [persistent-volume, reconstruction]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
          artifacts:
          - {name: reconstruction-data, from: '{{tasks.reconstruction.outputs.artifacts.reconstruction-data}}'}
      - name: hdf5-conversion-2
        template: hdf5-conversion-2
        dependencies: [persistent-volume, reconstruction-2]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
          artifacts:
          - {name: reconstruction-2-data, from: '{{tasks.reconstruction-2.outputs.artifacts.reconstruction-2-data}}'}
      - name: hdf5-conversion-3
        template: hdf5-conversion-3
        dependencies: [persistent-volume, reconstruction-3]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
          artifacts:
          - {name: reconstruction-3-data, from: '{{tasks.reconstruction-3.outputs.artifacts.reconstruction-3-data}}'}
      - {name: persistent-volume, template: persistent-volume}
      - name: reconstruction
        template: reconstruction
        dependencies: [persistent-volume, simulation]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
          artifacts:
          - {name: simulation-data, from: '{{tasks.simulation.outputs.artifacts.simulation-data}}'}
      - name: reconstruction-2
        template: reconstruction-2
        dependencies: [persistent-volume, simulation-2]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
          artifacts:
          - {name: simulation-2-data, from: '{{tasks.simulation-2.outputs.artifacts.simulation-2-data}}'}
      - name: reconstruction-3
        template: reconstruction-3
        dependencies: [persistent-volume, simulation-3]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
          artifacts:
          - {name: simulation-3-data, from: '{{tasks.simulation-3.outputs.artifacts.simulation-3-data}}'}
      - name: simulation
        template: simulation
        dependencies: [persistent-volume]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
      - name: simulation-2
        template: simulation-2
        dependencies: [persistent-volume]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
      - name: simulation-3
        template: simulation-3
        dependencies: [persistent-volume]
        arguments:
          parameters:
          - {name: persistent-volume-name, value: '{{tasks.persistent-volume.outputs.parameters.persistent-volume-name}}'}
  - name: persistent-volume
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.name}}-my-pvc'
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
    outputs:
      parameters:
      - name: persistent-volume-manifest
        valueFrom: {jsonPath: '{}'}
      - name: persistent-volume-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: persistent-volume-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: reconstruction
    container:
      args: ['git clone https://github.com/EnginEren/hgAHCal-ECal.git &&                                 cd
          $PWD/hgAHCal-ECal && pwd &&                                 chmod +x ./runRec.sh
          && ./runRec.sh "$0" "$1" "$2" ', /tmp/inputs/input-0/data, '1', prod]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-spack:latest
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
      artifacts:
      - {name: simulation-data, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: reconstruction-data, path: /mnt/run_prod/pion-shower_1_REC.slcio}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: reconstruction-2
    container:
      args: ['git clone https://github.com/EnginEren/hgAHCal-ECal.git &&                                 cd
          $PWD/hgAHCal-ECal && pwd &&                                 chmod +x ./runRec.sh
          && ./runRec.sh "$0" "$1" "$2" ', /tmp/inputs/input-0/data, '2', prod]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-spack:latest
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
      artifacts:
      - {name: simulation-2-data, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: reconstruction-2-data, path: /mnt/run_prod/pion-shower_2_REC.slcio}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: reconstruction-3
    container:
      args: ['git clone https://github.com/EnginEren/hgAHCal-ECal.git &&                                 cd
          $PWD/hgAHCal-ECal && pwd &&                                 chmod +x ./runRec.sh
          && ./runRec.sh "$0" "$1" "$2" ', /tmp/inputs/input-0/data, '3', prod]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-spack:latest
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
      artifacts:
      - {name: simulation-3-data, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: reconstruction-3-data, path: /mnt/run_prod/pion-shower_3_REC.slcio}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: simulation
    container:
      args: ['git clone https://github.com/EnginEren/hgAHCal-ECal.git  &&                                 cd
          $PWD/hgAHCal-ECal && chmod +x ./runSimNested.sh && ./runSimNested.sh "$0"
          "$1" ', '1', prod]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-spack:latest
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
    outputs:
      artifacts:
      - {name: simulation-data, path: /mnt/run_prod/pion-shower_1.slcio}
      - {name: simulation-lcio_path, path: /mnt/lcio_path}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: simulation-2
    container:
      args: ['git clone https://github.com/EnginEren/hgAHCal-ECal.git  &&                                 cd
          $PWD/hgAHCal-ECal && chmod +x ./runSimNested.sh && ./runSimNested.sh "$0"
          "$1" ', '2', prod]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-spack:latest
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
    outputs:
      artifacts:
      - {name: simulation-2-data, path: /mnt/run_prod/pion-shower_2.slcio}
      - {name: simulation-2-lcio_path, path: /mnt/lcio_path}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  - name: simulation-3
    container:
      args: ['git clone https://github.com/EnginEren/hgAHCal-ECal.git  &&                                 cd
          $PWD/hgAHCal-ECal && chmod +x ./runSimNested.sh && ./runSimNested.sh "$0"
          "$1" ', '3', prod]
      command: [/bin/bash, -c]
      image: ilcsoft/ilcsoft-spack:latest
      volumeMounts:
      - {mountPath: /mnt, name: persistent-volume}
    inputs:
      parameters:
      - {name: persistent-volume-name}
    outputs:
      artifacts:
      - {name: simulation-3-data, path: /mnt/run_prod/pion-shower_3.slcio}
      - {name: simulation-3-lcio_path, path: /mnt/lcio_path}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: persistent-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.persistent-volume-name}}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
